# Generated by Django 5.2.6 on 2025-10-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentApplication',
            new_name='Student',
        ),
    ]
